/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javafx.embed.swing.JFXPanel;
import javax.swing.JComponent;

/**
 *
 * @author Padovano
 */
public class Settings extends javax.swing.JInternalFrame {

    private final JFXPanel jfxPanel = new JFXPanel();
    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        //add(jf)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        build_create = new javax.swing.JMenuItem();
        build_update = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mod_create = new javax.swing.JMenuItem();
        mod_update = new javax.swing.JMenuItem();
        mod_assigment = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setTitle("Settings");

        jMenu1.setText("Settings");

        jMenu3.setText("Building");

        build_create.setText("Create Building");
        build_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                build_createActionPerformed(evt);
            }
        });
        jMenu3.add(build_create);

        build_update.setText("Udate Building");
        jMenu3.add(build_update);

        jMenu1.add(jMenu3);

        jMenu4.setText("Module");

        mod_create.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mod_create.setText("Create Module");
        jMenu4.add(mod_create);

        mod_update.setText("Edit Module");
        jMenu4.add(mod_update);

        mod_assigment.setText("Assign to Building");
        jMenu4.add(mod_assigment);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator1);

        jMenuItem6.setText("Style Routing");
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator2);

        jMenu5.setText("Supervisor");

        jMenuItem7.setText("Create Supervisor");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Edit Supervisor");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Supervisors");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Window");

        jMenuItem10.setText("Close");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void build_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_build_createActionPerformed
        // TODO add your handling code here:
        changeTitle("Create Building");
    }//GEN-LAST:event_build_createActionPerformed

    
    private void changeTitle(String title){
        setTitle(title);
    }
    
    private void Load(JComponent comp){
        //this.setL
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem build_create;
    private javax.swing.JMenuItem build_update;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mod_assigment;
    private javax.swing.JMenuItem mod_create;
    private javax.swing.JMenuItem mod_update;
    // End of variables declaration//GEN-END:variables
}
