/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConnectionDb;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Padovano
 */
public class UpdatePackingInfos extends javax.swing.JInternalFrame {
    private final ConnectionDb conn=ConnectionDb.instance();
    private int pack_id=0;
    /**
     * Creates new form UpdatePackingInfos
     */
    public UpdatePackingInfos() {
        initComponents();
        init();
    }

    private void init(){
        MODULE.setSelectedIndex(0);
        POLABEL.setText("");
        QTYLABEL.setText("");
        SCAN.setText("");
        SKULABEL.setText("");
        STICKERLABEL.setText("");
        TABLE.setSelectedIndex(0);
        blockDate.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jDateChooser1.setEnabled(false);
        pack_id=0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SCAN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        POLABEL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SKULABEL = new javax.swing.JLabel();
        QTYLABEL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        blockDate = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        STICKERLABEL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MODULE = new javax.swing.JComboBox();
        TABLE = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Update Packing Infos");

        SCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCANActionPerformed(evt);
            }
        });
        SCAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SCANKeyReleased(evt);
            }
        });

        jLabel1.setText("Scan box label");

        jLabel2.setText("PO:");

        POLABEL.setText("jLabel3");

        jLabel4.setText("SKU:");

        SKULABEL.setText("jLabel3");

        QTYLABEL.setText("jLabel3");

        jLabel7.setText("QTY:");

        jLabel8.setText("MODULE:");

        jLabel11.setText("TABLE:");

        jButton1.setText("UNSCAN");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Date");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout blockDateLayout = new javax.swing.GroupLayout(blockDate);
        blockDate.setLayout(blockDateLayout);
        blockDateLayout.setHorizontalGroup(
            blockDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        blockDateLayout.setVerticalGroup(
            blockDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blockDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        STICKERLABEL.setText("jLabel3");

        jLabel5.setText("BOX STICKERS:");

        MODULE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please choose module", "MOD 1", "MOD 1A", "MOD 1B", "MOD 2", "MOD 2A", "MOD 2B", "MOD 3", "MOD 4", "MOD 5", "MOD 6", "MOD 7", "MOD 8", "MOD 9", "MOD 10", "MOD 11", "MOD 12", "MOD 13", "MOD 14", "MOD 15", "MOD 16", "MOD 17", "MOD 18", "MOD 19", "MOD 20", "MOD 21", "MOD 22", "MOD 23", "MOD 24", "MOD 25", "SAMPLE ROOM" }));

        TABLE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select table--", "Packing 29-1", "Packing 29-2", "Packing 29-3", "Packing 29-4", "Packing 30-1", "Packing 30-2", "Packing 30-3", "Packing 30-4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(SCAN, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addComponent(SKULABEL))
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(QTYLABEL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TABLE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(MODULE, 0, 140, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(POLABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(STICKERLABEL)
                                .addGap(89, 89, 89))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(45, Short.MAX_VALUE)
                        .addComponent(blockDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SCAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(POLABEL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(STICKERLABEL)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SKULABEL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(QTYLABEL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MODULE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(blockDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCANActionPerformed

    private void SCANKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SCANKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String code=((JTextField)evt.getSource()).getText().trim();
            if(code.isEmpty()){
                JOptionPane.showInternalMessageDialog(this, "scan the box sticker first");
                return;
            }
            Map<String,String> data=getBoxPackingInfos(code);
            if(data.isEmpty()){
                JOptionPane.showInternalMessageDialog(this, "No imformation for this box\n");
                init();
                return;
            }
            POLABEL.setText(data.get("PO"));
            SKULABEL.setText(data.get("SKU"));
            QTYLABEL.setText(data.get("QTY"));
            SCAN.setText("");
            MODULE.setSelectedItem(data.get("MODULE"));
            TABLE.setSelectedItem(data.get("TABLE"));
            STICKERLABEL.setText(data.get("STICKER"));
            pack_id=Integer.parseInt(data.get("ID"));
            jButton2.setEnabled(true);
            if(data.get("STATUS").trim().equalsIgnoreCase("0")){
                blockDate.setEnabled(true);
                jDateChooser1.setEnabled(true);
                jButton1.setEnabled(true);
            }
        }
    }//GEN-LAST:event_SCANKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        delete();
        init();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        update();
        init();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void update(){
        ArrayList<Object> dat=new ArrayList<>();
        if(MODULE.getSelectedIndex()>0){
            String table=(TABLE.getSelectedIndex()>0?TABLE.getSelectedItem().toString():"Both");
            String update="update packing set Module=?,tablepacking=?";
            dat.add(MODULE.getSelectedItem().toString());
            dat.add(table);
            if(blockDate.isEnabled()&&jDateChooser1.getDate()!=null){
                update+=",created=?";
                dat.add(jDateChooser1.getDate());
            }
            dat.add(pack_id);
            update +=" where id=?";
            if(conn.Update(update, 0, dat.toArray())){
                JOptionPane.showMessageDialog(this, "LPN update successfully ", "success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
    private void delete(){
        
            String update="delete from  packing ";
            
            update +=" where id=?";
            if(conn.Update(update, 0, pack_id)){
                JOptionPane.showMessageDialog(this, "LPN unscan successfully ", "success", JOptionPane.INFORMATION_MESSAGE);
            }
        
    }
    private Map<String,String> getBoxPackingInfos(String box){
        String requete="select * from packed_lpn where lpnScan=? or box_stickers=?";
        ResultSet rs=conn.select(requete, box,box);
        Map<String,String> boxinfos=new HashMap<>();
        try {
            while (rs.next()){
                boxinfos.put("PO", rs.getString("PO"));
                boxinfos.put("ID", String.valueOf(rs.getInt("Pack_id")));
                boxinfos.put("SKU", rs.getString("sku"));
                boxinfos.put("QTY", String.valueOf(rs.getInt("QTY")));
                boxinfos.put("STICKER", rs.getString("BOX_STICKERS"));
                boxinfos.put("TABLE", rs.getString("tablepacking"));
                boxinfos.put("MODULE", rs.getString("module"));
                boxinfos.put("DATE", rs.getString("scan_date"));
                boxinfos.put("STATUS", rs.getString("status"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdatePackingInfos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return boxinfos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MODULE;
    private javax.swing.JLabel POLABEL;
    private javax.swing.JLabel QTYLABEL;
    private javax.swing.JTextField SCAN;
    private javax.swing.JLabel SKULABEL;
    private javax.swing.JLabel STICKERLABEL;
    private javax.swing.JComboBox TABLE;
    private javax.swing.JPanel blockDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
